### PR TITLE
Use gradle, java 10 compatibility

### LINKED ISSUE #80: Code Review: Fix broken link to coverage report
The link to the coverage report in the pdl github.io [Java API](https://usgs.github.io/pdl/userguide/java_api.html) page is broken, please fix.

Also, consider moving this coverage report to codecov or codacy.  If codecov or codacy is used, please add a link / badge to the main page, or otherwise make it more visible.

### LINKED ISSUE #81: Code Review Suggestion: Implement Linting / Code Checks
Suggestion, implement code style linting / error checks using codacy or similar.

### LINKED ISSUE #83: Code Review Suggestion: Consider adding automatic deployment of docs to github.io
Consider adding automatic deployment of user guide to github.io as part of the travis.ci build.

### LINKED ISSUE #85: Code Review: Make clear which code is external
Example is Base64.java in util

### PR DESCRIPTION
**Pull request by jmfee-usgs**
Depends on https://github.com/usgs/eqmessageutils/pull/15

Fixes #85 
- removed external code

Fixes #83
- gradle gitPublishPush task automates deployment of docs, coverage, and unit test reports to github.io after a new release
- Preview at http://jmfee-usgs.github.io/pdl/

Fixes #81
- Codacy, CodeCov integration added to travis build script, badges added to README

Fixes #80
- coverage report is once again published to github pages
- Preview at http://jmfee-usgs.github.io/pdl/

Relates to #77
- Added code.json
- Removed external code

### CODE REVIEW

**Comment by jpatton-USGS** [comment]
Also, I would like to see codacy working....

**Comment by pmpowers-usgs** [comment]
I didn't use Java 10, so that may have given rise to the following test failure:
```
gov.usgs.earthquake.distribution.ReplicationStorageListenerTest > testReplicationAddRemove FAILED
    java.lang.AssertionError at ReplicationStorageListenerTest.java:122
```

The java 8 javadoc tool also did not understand the -html5 flag and failed. Once commented out, I got a lot of javadoc warnings that could be suppressed with:
```
options.addStringOption('Xdoclint:none', '-quiet')
```

Otherwise the build has a lot of elements in it that I've never used, but looks ok overall. If you are reusing any variable fields, many gradle builds take advantage of the `ext` block, for example:
https://github.com/usgs/nshmp-haz/blob/master/build.gradle#L47

**Comment by jmfee-usgs** [comment]
@pmpowers-usgs : thanks for taking a look.  The tests require you have local ssh set up (ssh 127.0.0.1) using an ssh key

**Comment by jmfee-usgs** [comment]
Merging since it has been reviewed, and is not being merged into master yet.

**Pull request merged**
